### ISSUE TITLE
Website Favicon

### ISSUE THREAD

**Issue by soarn** [ChewCraft/IRC#16]
The website doesn't have an icon! It just has the browser-specific default icon, this is an issue and should be fixed!
(Maybe use that snazzy blue/purple icon @2003cah made in that irccloud discord meme)

**Comment by Chew** [comment]
Do you mean a favicon?

**Comment by soarn** [comment]
yes i forgot the word

**Comment by Chew** [comment]
Consider your idea c o n s i d e r e d.

**Comment by soarn** [comment]
many thanks

**Comment by Chew** [comment]
Since cah has the image....

**Comment by soarn** [comment]
@2003cah get that image or you're fired

**Comment by cahcontent** [comment]
If anything I'll probably just design something unique for the favicon

**Comment by soarn** [comment]
Then by all means please do

**Comment by cahcontent** [comment]
Wow rude

**Comment by Chew** [comment]
This is your motivation to make a favicon

**Comment by cahcontent** [comment]
When you literally already forgot and it's only been 12 hours

**Comment by cahcontent** [comment]
What should I make as a favicon, anyway?

**Comment by soarn** [comment]
I have no idea, just make something that combines a cat and the irccloud logo?

**Comment by cahcontent** [comment]
It took about 5 minutes, but try this, see if you can even see the catto in favicon form ![catcloud](https://user-images.githubusercontent.com/7423779/32684790-74842bcc-c655-11e7-974b-3ce11a8290c1.png)

**Comment by soarn** [comment]
It's great
10/10
whose cat is it?
>V
>E
>R
>Y
 
>G
>O
>O
>D

**Comment by Chew** [comment]
Pretty sure that's cah's cat

**Comment by Chew** [comment]
Consider this issue dabbed on
